name             'sonar'
maintainer       'Andrew Hoffmann'
maintainer_email 'andrew.hoffmann.wi@gmail.com'
license          'All rights reserved'
description      'Installs/Configures sonar'
long_description 'Installs/Configures sonar'
version          '1.0.0'
depends          'apt'
depends          'java'
depends          'sonarqube'
depends          'mysql2_chef_gem'
depends          'mysql'
depends          'database'